CREATE TABLE IF NOT EXISTS refresh_tokens(
	refresh_token TEXT PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_refresh TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
