services:
  whaler:
    container_name: whaler
    restart: unless-stopped
    build: .
    ports:
      - 8765:8080
    depends_on:
      - rdbms

  rdbms:
    container_name: rdbms-whaler
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - /whaler_data:/var/lib/postgresql/data

volumes:
  whaler_data: