services:
  whaler-backend:
    image: iamirup/whaler-backend:latest
    build: ./backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web_net"
        - "traefik.http.routers.backend.entrypoints=http"
        - "traefik.http.routers.backend.rule=(Host(`whaler.ir`) && PathPrefix(`/api/v1`))"
        - "traefik.http.routers.backend.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.backend-secure.entrypoints=https"
        - "traefik.http.routers.backend-secure.rule=(Host(`whaler.ir`) && PathPrefix(`/api/v1`))"
        - "traefik.http.routers.backend-secure.tls=true"
        - "traefik.http.routers.backend-secure.tls.options=default"
        - "traefik.http.routers.backend-secure.tls.certresolver=mycert"
        - "traefik.http.services.backend.loadbalancer.server.port=8080"
    depends_on:
      - rdbms
    networks:
      - web_net
      - whaler_net

  whaler-frontend:
    image: iamirup/whaler-frontend:latest
    build: ./frontend
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web_net"
        - "traefik.http.routers.frontend.entrypoints=http"
        - "traefik.http.routers.frontend.rule=Host(`whaler.ir`)"
        - "traefik.http.routers.frontend.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.frontend-secure.entrypoints=https"
        - "traefik.http.routers.frontend-secure.rule=Host(`whaler.ir`)"
        - "traefik.http.routers.frontend-secure.tls=true"
        - "traefik.http.routers.frontend-secure.tls.options=default"
        - "traefik.http.routers.frontend-secure.tls.certresolver=mycert"
        - "traefik.http.services.frontend.loadbalancer.server.port=80" 
    networks:
      - web_net

  rdbms:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - /whaler_data:/var/lib/postgresql/data
    networks:
      - whaler_net

networks:
  web_net:
    external: true
    name: web_net
    driver: overlay
  whaler_net:
    driver: overlay

volumes:
  whaler_data: