services:
  whaler-backend:
    image: iamirup/whaler-backend:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    build: ./backend
    depends_on:
      - rdbms
    networks:
      - web_net
      - whaler_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.routers.app.rule=(Host(`whaler.ir`) && PathPrefix(`/api/v1`))"
      - "traefik.http.routers.app.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.app-secure.entrypoints=https"
      - "traefik.http.routers.app-secure.rule=(Host(`whaler.ir`) && PathPrefix(`/api/v1`))"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.options=default"
      - "traefik.http.routers.app-secure.tls.certresolver=mycert"
      - "traefik.http.services.app.loadbalancer.server.port=8080"

  whaler-frontend:
    image: iamirup/whaler-frontend:latest
    deploy:
      restart_policy:
        condition: on-failure
    build: ./frontend
    networks:
      - web_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.routers.app.rule=Host(`whaler.ir`)"
      - "traefik.http.routers.app.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.app-secure.entrypoints=https"
      - "traefik.http.routers.app-secure.rule=Host(`whaler.ir`)"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.options=default"
      - "traefik.http.routers.app-secure.tls.certresolver=mycert"
      - "traefik.http.services.app.loadbalancer.server.port=5000" 

  rdbms:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - /whaler_data:/var/lib/postgresql/data
    networks:
      - whaler_net

networks:
  web_net:
    external: true
    name: web_net
    driver: overlay
  whaler_net:
    driver: overlay

volumes:
  whaler_data: