services:
  auth-microservice:
    image: iamirup/whaler-auth-backend:latest
    build: ./backend/auth
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web_net"
        - "traefik.http.routers.auth-microservice.entrypoints=http"
        - "traefik.http.routers.auth-microservice.rule=(Host(`whaler.ir`) && PathPrefix(`/api/auth/v1`))"
        - "traefik.http.routers.auth-microservice.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.auth-microservice-secure.entrypoints=https"
        - "traefik.http.routers.auth-microservice-secure.rule=(Host(`whaler.ir`) && PathPrefix(`/api/auth/v1`))"
        - "traefik.http.routers.auth-microservice-secure.tls=true"
        - "traefik.http.routers.auth-microservice-secure.tls.options=default"
        - "traefik.http.routers.auth-microservice-secure.tls.certresolver=mycert"
        - "traefik.http.services.auth-microservice.loadbalancer.server.port=8080"
    depends_on:
      - rdbms
    networks:
      - web_net
      - whaler_net

  rdbms:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - /whaler_auth_data:/var/lib/postgresql/data
    networks:
      - whaler_net

networks:
  web_net:
    external: true
    name: web_net
    driver: overlay
  whaler_net:
    driver: overlay

volumes:
  whaler_data: