CREATE TABLE IF NOT EXISTS users(
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(72) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
